### ISSUE TITLE
Setting connectionId yields a exception

### ISSUE THREAD

**Issue by ewirch** [UsageStats/UsageStats#14]
Version 0.2

The localized message says:

> Durch das Festlegen von connectionId wurde eine Ausnahme ausgelöst.

The message is followed by:

> Die Datei oder Assembly "Hardcodet.Wpf.TaskarNotification, Version=1.0.5.0, Culture=neutral, PublicKeyToken=null" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden.

Google translates this to: "The file or assembly "Hardcodet.Wpf.TaskarNotification, Version = 1.0.5.0, Culture = neutral, PublicKeyToken = null" or a dependency of it was not found. The system can not find the specified file."

**Comment by objorke** [comment]
Is the dll missing in your program folder?
The UsageStats program folder should contain:
![image](https://cloud.githubusercontent.com/assets/439716/21067017/2e2cbe4a-be69-11e6-912f-58a1bc6ddeb1.png)

**Comment by ewirch** [comment]
DLL is missing. I downloaded the binaries from releases: https://github.com/UsageStats/UsageStats/releases

**Comment by objorke** [comment]
I think the release should be built by https://ci.appveyor.com/project/objorke/usagestats

**Comment by sadortun** [comment]
@objorke can you submit a PR with your proposed changes ?

**Comment by objorke** [comment]
the dll should be included in the latest build artifacts
https://ci.appveyor.com/project/objorke/usagestats

**Comment by KCIV** [comment]
This issue still exists exact same error message. Attempting to resolve via comments

**Comment by KCIV** [comment]
This is what your program unzips as 
https://puu.sh/wI5OE/9a0a0c32c9.png

no DLL files included (all hidden files are open)

**Comment by objorke** [comment]
The artifacts should be downloaded from https://ci.appveyor.com/project/objorke/usagestats/build/artifacts
I have deleted the invalid zip archives from the release page.

**Comment by objorke** [comment]
Can this issue be closed?

**Comment by KCIV** [comment]
Will test when I get home. Thanks for responding.
